title: "知识笔记"
description: "个人阅读笔记与知识库"
baseurl: "/obsidian-notes"
url: "https://PatriotBo.github.io"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
permalink: /:categories/:year/:month/:day/:title/
collections:
  notes:
    output: true
    permalink: /notes/:title/
defaults:
  - scope:
      path: "_notes"
      type: "notes"
    values:
      layout: "note"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
